### ISSUE TITLE
How to use eve-sqlalchemy with MySQL?

### ISSUE THREAD

**Issue by daniel-dong** [pyeve/eve-sqlalchemy#101]
I'd like to use eve-sqlalchemy with a MySQL database, but the documentation does not mention it.

**Comment by LifenetsAndrew** [comment]
@daniel-dong, I think this might help you: [http://docs.sqlalchemy.org/en/rel_1_0/core/engines.html#mysql](url). eve-sqlalchemy has nothing to do with mysql, cause it's sqlalchemy's job.

**Comment by ralphsmith80** [comment]
That link appears to be dead, but I ran into this and found [this](http://stackoverflow.com/questions/22252397/importerror-no-module-named-mysqldb) solution.

gist
```
pip install pymysql
```
then use
```
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://.....'
```
