### ISSUE TITLE
Return calculated (none ORM mapped) property for a resource

### ISSUE THREAD

**Issue by vsobolmaven** [pyeve/eve-sqlalchemy#106]
Does eve-sqlalchemy allow to define an attribute on a resource class and return it in a result for GET request if the attribute is not mapped to ORM?
e.g.

```
class ClassX(Base):
  @property
  def my_property(self)
     return "abracadabra"

registerSchema('res')(ClassX)

schema['schema']['my_property'] = {
  'type': 'string'
}
```

I need the property value as part of response with resource. Is this supported?
Thanks!

**Comment by mandarvaze** [comment]
I am able to return additional attribute that is not mapped to ORM
But I am using the style you suggested above.
Instead I am using ``on_fetched`` hook to append additional attributes to the response.

**Comment by dkellner** [comment]
Instead of using the `on_fetched` hook you can add the column to the projection, too.

**Comment by mandarvaze** [comment]
@dkellner Can you give an example how projection could be used to "insert" **additional** data that is not part of the DB ?

**Comment by dkellner** [comment]
Extending [trivial.py](https://github.com/pyeve/eve-sqlalchemy/blob/5e6177500623be2312b8e0670a450f98c19d6608/examples/trivial.py):

```python
class People(Base):
    # ...
    @property
    def foo(self):
        return "bar"
```
```python
SETTINGS['DOMAIN']['people']['datasource']['projection']['foo'] = 1
```

If you want to add fields that are *not* part of the `People` class, you're out of luck with projections. In this case you have to resort to the event system.
