### ISSUE TITLE
Filtering multiple fields results in EveWSGIRequestHandler

### ISSUE THREAD

**Issue by hroncok** [pyeve/eve-sqlalchemy#111]
Hi, I have and issue described here: https://github.com/nicolaiarocci/eve/issues/859

I'm not quite sure if it's Eve's or eve-sqlalchemy's issue, so I'm opening it here as well, so both projects are aware of this.

**Comment by dkellner** [comment]
I know it's a long time before getting back to you, sorry for that. Could you solve your problem? I just tried with Eve and imo there's no problem at their side. And it works in Eve-SQLAlchemy's trivial example, too (at least in the current master branch).

*But* we still have the issue described in #127, that we return a HTTP 500 on some broken query strings and get seemingly unrelated exceptions on the server side. It could be the issue you're facing. Did you use `curl` to make those requests? If yes, make sure you use the '-g' flag to turn off the "URL globbing parser".

**Comment by hroncok** [comment]
I might have used curl. I was doing some reserach back than about Python web/REST API libraries. I wasn't able to solve this back then and I don't really care any more. Feel free to close this if you want.

**Comment by dkellner** [comment]
Just out of curiosity, did you decide to use another framework?

**Comment by hroncok** [comment]
The research was just for academic purposes :)

I found eve and ripozo the most interesting ones for non-Django frameworks.

**Comment by dkellner** [comment]
Ok, thank you for you quick reply even this was quite a time ago already! I just recently got into maintaining this project and am still cleaning up here and there ;).
