### ISSUE TITLE
Query with field greater than and less than

### ISSUE THREAD

**Issue by stephen-talari** [pyeve/eve-sqlalchemy#114]
I tried multiple expression combinations to find the field with in a given range but didn't work.
`Working: {"_id":">50"}`
`Failed: {"_id":">50&&<100"}`

All i am trying to do is to `find the records where id >50 and id <100`

No proper documentation is found on web

**Comment by stephen-talari** [comment]
Any help ?

**Comment by mandarvaze** [comment]
eve supports two styles of ``where`` queries as part of URL params.
One is dict style (One you have tried above) and other is ``python`` style. You can read more [here](http://python-eve.org/features.html#filtering)

Back to original question..

I was able to get greater than and less than queries working with later style 
e.g.

    http://localhost:5001/people?where=age>=20 and age<30

**Comment by dkellner** [comment]
We still have some issues related to the SQLAlchemy query syntax. By now it seems best to use @mandarvaze's "workaround". I will open some issues the next days/weeks.
