### ISSUE TITLE
Sub resources on shared datasource fail

### ISSUE THREAD

**Issue by cbora** [pyeve/eve-sqlalchemy#116]
when updating the 'url' to be a sub-resource, i.e. url: people/< regex([0-9]+:contact_id >/invoice. This has no effect on the endpoint. In matter of fact, there is a parse error when forcing to get XML output

**Comment by dkellner** [comment]
This works for me for JSON and XML output. I've added these lines to `examples/settings.py`:

```python
DOMAIN['invoices'].update({
    'url': 'people/<regex("[0-9]+"):people>/invoices',
})
```

And tried these requests:
```http
POST http://127.0.0.1:5000/people/1/invoices
Content-Type: application/json

{
    "number": 42
}
```

```http
GET http://127.0.0.1:5000/people/1/invoices
Accept: application/xml
```
