### ISSUE TITLE
Typo in Repository Description

### ISSUE THREAD

**Issue by dkellner** [pyeve/eve-sqlalchemy#126]
@amleczko There is a typo in the repository's description: "Eve SQLAlchemy extenstion". Can you please fix that? I'm afraid I don't have permission to edit it myself.

**Comment by dkellner** [comment]
I now could edit it myself, but I guess @nicolaiarocci already replaced it with a much better description.

**Comment by nicolaiarocci** [comment]
Could not resiste the urge. Feel free to edit it however you feel more appropriate 😄
