### ISSUE TITLE
Tidy up examples directory

### ISSUE THREAD

**Issue by dkellner** [pyeve/eve-sqlalchemy#139]
Running the examples as expected does not work:

```sh
git clone https://github.com/RedTurtle/eve-sqlalchemy.git
cd eve-sqlalchemy
virtualenv -p python3 .  # or python2, does not matter
source bin/activate
pip install .
cd examples
python trivial.py  # works, as it does not contain relative imports
python sqla_example.py  # fails with "cannot perform relative import"
```

Furthermore, I would like to organize the contents of the `examples/` directory, preferrably one well-named subdirectory for each example, containig a main.py (or app.py, or same name as the directory) to run and a proper module (maybe called `sample`) for the application code. This would also solve the import issue.

As a bonus, one could look at all the comments in there and improve them.

**Comment by joystein** [comment]
I propose that with the fix above, this issue can be closed, but that maybe a new issues (one that is added to a post-0.5 milestone) is created for improving the organization of the examples directory.
