### ISSUE TITLE
Moving eve-sqlalchemy to pyeve organization

### ISSUE THREAD

**Issue by amleczko** [pyeve/eve-sqlalchemy#140]
Yesterday @nicolaiarocci started pyeve organization on github. My proposition is to move this repo there. Any objections @RedTurtle/redturtle-admins @dkellner @nicolaiarocci ?

**Comment by dkellner** [comment]
@nicolaiarocci and I are both in favor for doing this. How about access to PyPI (#135) in this regard?

Also see https://github.com/RedTurtle/eve-sqlalchemy/issues/91#issuecomment-284767464 .

**Comment by amleczko** [comment]
I think at this moment only @nicolaiarocci can do it - you need to be repo admin in both organizations in order to perform the transfer.

**Comment by nicolaiarocci** [comment]
I'm all for it.

**Comment by nicolaiarocci** [comment]
The move is done. Cheers!

**Comment by amleczko** [comment]
Thanks RedTurtle for all the years of your support!
