### ISSUE TITLE
Mapping table column directly to request body

### ISSUE THREAD

**Issue by bomb-on** [pyeve/eve-sqlalchemy#149]
Suppose I have a super simple table like this

```
class FillMe(EveCommonCols):
    id = Column(Integer, primary_key=True, autoincrement=True)
    user_data = Column(JSON)
```

where I can easily insert data into it with POST method by including JSON body, such as `{"user_data": {"some": "data", "whatever": True}}`.

Is it possible to tell `user_data` column to accept whatever is sent in the request body, so that client is able to send just "plain data", without need to wrap it in additional dictionary with key name like my column name?

So, sending just `{"some": "data", "whatever": True}` in request body and storing it in `user_data` column?

Or maybe even a slightly different scenario, like:
```
class FillMe(EveCommonCols):
    id = Column(Integer, primary_key=True, autoincrement=True)
    part_od_user_data = Column(Integer)
    other_part_od_user_data = Column(Boolean)
    rest_of_the_data = Column(JSON)
```
and being able to receive data like this in request body:
```
{
  "part_od_user_data": 1,
  "other_part_od_user_data": True,
  "rest_of_the_data": {
    "whatever": "else"
  }
}
```
which would be sorted in appropriate columns...

**Comment by dkellner** [comment]
I think this should be possible using Eve's event hooks (http://python-eve.org/features.html#event-hooks) - but I guess you have to resort to pre request hooks as you need to alter your request in order to make it pass validation.

Your second scenario looks like a classic request payload - is it not working in your case? Did you mean to not include the column name for "rest_of_the_data" in the payload?

**Comment by bomb-on** [comment]
Of course, hooks =) Thanks for pointing that out and tips about it! My second scenario works like a charm actually =) It is just a confusion with using older Eve-SQLAlchemy version and JSON column type related problems, but yeah, it works as it should =) Therefore, closing this one!
