### ISSUE TITLE
Requires Flask <0.11

### ISSUE THREAD

**Issue by renderit** [pyeve/eve-sqlalchemy#150]
I'm not sure, if I'm doing something wrong, but on doing `python setup.py install` I'm getting error saying I need Flask version <0.11. Is this true? :\ Since our current project uses Flask 0.12(latest since last year).

**Comment by jcrben** [comment]
Hopefully this can be bumped up before not too long...

**Comment by dkellner** [comment]
@jcrben See https://github.com/pyeve/eve-sqlalchemy/issues/136 . There isn't any progress yet, but if you want to give it a try go ahead. It should be feasible :).
