### ISSUE TITLE
Allow removing None field as optional

### ISSUE THREAD

**Issue by Gnouc** [pyeve/eve-sqlalchemy#154]
In [sqla_object_to_dict function](https://github.com/pyeve/eve-sqlalchemy/blob/e006626c1cfc3305a2737c4a2990e50f0b5d5519/eve_sqlalchemy/utils.py#L45), fields with value `None` were silently removed. This behavior, IMHO is bad practice and should be optional (or need to be removed).

This behavior leads to in-consistent API response (my API are built with `eve` and `eve-sqlalchemy`) which is very bad practice in API design perspective.

**Comment by dkellner** [comment]
Can you confirm that Eve is actually sending `None` values?

**Comment by Gnouc** [comment]
@dkellner I don't have time to dig into `eve` source code, so I create a simple API https://github.com/Gnouc/eve-sqlalchemy-issue-154-demo

**Comment by polvoazul** [comment]
Before version 0.5 it was sending None values, and now it is not. This new behavior broke my on_fetch events which relied on that. So I had to freeze version 0.4

**Comment by dkellner** [comment]
Thank you both for raising this. See #155 for further discussion.
