### ISSUE TITLE
Add support for filtering on embedded document fields

### ISSUE THREAD

**Issue by madsmtm** [pyeve/eve-sqlalchemy#186]
See [eve/features#filtering](http://docs.python-eve.org/en/latest/features.html#filtering), their example does not work with Eve-SQLAlchemy:
```
http://eve-demo.herokuapp.com/people?where={"location.city": "San Francisco"}
```

We could fix this by changing [parser.py#L63](https://github.com/pyeve/eve-sqlalchemy/blob/master/eve_sqlalchemy/parser.py#L63) (and maybe [parser.py#L221](https://github.com/pyeve/eve-sqlalchemy/blob/master/eve_sqlalchemy/parser.py#L221)) to something that recursively finds the attribute, e.g.:
```py
k_split = iter(k.split('.'))
attr = getattr(model, next(k_split))
for x in k_split:
    attr = getattr(attr.property.argument, x)
```
Though I'm not sure if this would encompass all cases, or have unexpected side effects

**Comment by madsmtm** [comment]
I can make a PR, and see if it passes the existing test suite, but I'd like an opinion on the approach first, it feels hacky ;)

**Comment by dkellner** [comment]
Thanks for reporting this!

We should introduce a failing test before we change the implementation. Is there a test in Eve itself that covers this already? A quick look in `tests/get.py` does not show any skipped tests regarding to this kind of lookups.

Regarding the implementation: `parse_sorting` (https://github.com/pyeve/eve-sqlalchemy/blob/master/eve_sqlalchemy/parser.py#L143) seems to have some handling of child attributes already, but at first glance it looks like it cannot handle more than one level. It would be good to use the same code for translating the lookup strings to attributes in both cases, e.g. move this lookup in a separate function.

**Comment by Alan01252** [comment]
I wonder if it's worth documenting the fact that you can use AssocitionProxies instead to achieve similar functionality? In the above

```
location_relation = relationship("Location", secondary="location")
city = association_proxy('location_relation', 'city')
```

The query above is:

```
http://eve-demo.herokuapp.com/people?where={"city": "San Francisco"}
```
