### ISSUE TITLE
How to add validations with Eve-sqlalchemy

### ISSUE THREAD

**Issue by peterswords** [pyeve/eve-sqlalchemy#193]
In (traditional) Eve I can specify a validation to, for instance, restrict the allowed values on a field. Eve-sqlalchemy derives its metadata from the domain definitions supplied to sqlalchemy. These don't permit the extra validations (that I know of, or can find in the examples or docs).

However, I have found that if I render the Eve-sqlalchemy metadata from the domain definitions, I get a dictionary object which I can then poke my additional validations into. It's kludgy but it actually works -- Eve will apply the additional validations. Is this how it's supposed to be done? (Also asked [here](https://stackoverflow.com/questions/55084903/validations-with-the-sqlalchemy-version-of-python-eve) with a code example).

**Comment by dkellner** [comment]
I've answered on https://stackoverflow.com/questions/55084903/validations-with-the-
sqlalchemy-version-of-python-eve : 

-----

> I've tried to clarify the relationship between DomainConfig and Eve settings in the docs: https://eve-sqlalchemy.readthedocs.io/en/latest/tutorial.html#eve-settings :

>> You can do so using DomainConfig and ResourceConfig, which will give you a default schema (DOMAIN dictionary) derived from your SQLAlchemy models. This is intended as a starting point and to save you from redundant configuration, but there's nothing wrong with customizing this dictionary if you need to!

```python
# examples/simple/settings.py

# ...

# Even adding custom validations just for the REST-layer is possible:
DOMAIN['invoices']['schema']['number'].update({
    'min': 10000
})
```

> That said, if you actually have a constraint specified in your SQLAlchemy models that is not automatically translated into proper validation rules in Eve's schema definition, please open an issue!
