### ISSUE TITLE
 Please specify `related_resources` manually

### ISSUE THREAD

**Issue by virtualvinodh** [pyeve/eve-sqlalchemy#202]
Hi,

I get this error message when I try to run eve-sqlalchemy with automapped classes. 

File "C:\datalayer\venv\lib\site-packages\eve_sqlalchemy\config\fieldconfig.py", line 155, in _get_resource
    raise ConfigException(
eve.exceptions.ConfigException: Cannot determine related resource for service.lnk_collection. Please specify `related_resources` manually.

I tried to search around. But it's pretty much leading me fieldconfig.py and nothing else.

Would you happen to know how I add this related_resources field manually?

Thanks!

**Comment by dkellner** [comment]
I just saw there is no example for this yet, but a test: https://github.com/pyeve/eve-sqlalchemy/blob/master/eve_sqlalchemy/tests/config/domainconfig/ambiguous_relations.py#L59

You should be able to specify `related_resources` like this (untested):
```python
DomainConfig({
    'links': ResourceConfig(Link),
    'services': ResourceConfig(Service),
}, related_resources={
    (Service, 'lnk_collection'), 'links',
})
```

If it doesn't work, please provide a minimal example showing your issue.

**Comment by virtualvinodh** [comment]
It works thanks!
