### ISSUE TITLE
eve-sqlalchemy breaks sqlalchemy default.

### ISSUE THREAD

**Issue by obmarg** [pyeve/eve-sqlalchemy#46]
We've been using eve-sqlalchemy to provide a REST API as part of a larger project, and have found that it breaks the behaviour of setting a default on a column.

Pretty sure it's this code that's to blame: https://github.com/RedTurtle/eve-sqlalchemy/blob/056b6ca836def3fb396ea3a015a04a016d601db2/eve_sqlalchemy/decorators.py#L150-L152

**Comment by amleczko** [comment]
Can you write a simple test or paste a trace exception?

**Comment by obmarg** [comment]
Test added here: https://github.com/obmarg/eve-sqlalchemy/commit/1b78e14d730bd1f150f61de2b2069f17768ba11a

**Comment by obmarg** [comment]
Incase it wasn't obvious from the test - `_created` does get set correctly.  It doesn't seem to get to the same point of `register_column` that I pointed out earlier, though I haven't figured out why.

**Comment by Leonidaz0r** [comment]
Any updates on this?

**Comment by gabrielpjordao** [comment]
+1 on this

**Comment by dkellner** [comment]
I've been able to confirm this myself and adapted the testcase given by @obmarg to the current master, see https://github.com/dkellner/eve-sqlalchemy/tree/fix-sqlalchemy-default.
