### ISSUE TITLE
Not honoring ITEM_URL

### ISSUE THREAD

**Issue by erik-stephens** [pyeve/eve-sqlalchemy#68]
Needing to support non-integer ID's, I configured Eve with a custom `ITEM_URL` but [this line](https://github.com/RedTurtle/eve-sqlalchemy/blob/3c8780b2f053b9fa992d3d0ddd7494a286e87a41/eve_sqlalchemy/decorators.py#L59) has it hard-coded - should be `config.ITEM_URL`.  I can override another way but it may trip up others.

**Comment by lingfish** [comment]
I didn't have this issue, but it would be because I overrode thusly (for anyone else wondering how to):

```python
DOMAIN['some-schema'].update({
    'item_url': 'regex(".+")',
...
```

**Comment by ralphsmith80** [comment]
The issue is in [decorators.py#L68](https://github.com/RedTurtle/eve-sqlalchemy/blob/master/eve_sqlalchemy/decorators.py#L68).

**Comment by erik-stephens** [comment]
@ralphsmith80 I think we're linking to the same line.  For future reference, you probably want to link to a specific commit instead of a branch since the lines will change over time - it's bitten me a couple of times before.

**Comment by ralphsmith80** [comment]
@erik-stephens I just submitted a pull request for this. The fix was crazy easy. If you can wait you can use my [fork](https://github.com/ralphsmith80/eve-sqlalchemy).
