### ISSUE TITLE
TypeError: datetime.time(0, 15) is not JSON serializable

### ISSUE THREAD

**Issue by johnnywell** [pyeve/eve-sqlalchemy#89]
I'm having this error when trying to get some objects from a Firebird Database. Is it related to DATE_FORMAT or it should serialize any datetime object?

Following the traceback:
https://gist.github.com/anonymous/fafe8dc7b8d8da14dd24

**Comment by dkellner** [comment]
I'm closing this for now as the issue is quite old - sorry for that! If this is still an issue for you (or anyone else) please test against the current master branch and provide a minimal (failing) example.
