### ISSUE TITLE
Resource level id_field and item_lookup_field are not honoured

### ISSUE THREAD

**Issue by bthorben** [pyeve/eve-sqlalchemy#99]
Changing a resources id_field and item_loop_field to a custom value like "login" or "name" fails with 

`File "eve_sqlalchemy/__init__.py", in insert
    id_field = getattr(model_instance, self.driver.app.config['ID_FIELD'])
AttributeError: 'User' object has no attribute 'id'`

**Comment by nkhalasi** [comment]
I am running into the same issue. Is there a work around other than adding the 'id' attribute?

**Comment by nkhalasi** [comment]
Putting the below in the model worked as a work around.
`    @hybrid_property
    def id(self):
        """
        Eve backward compatibility
        """
        return self.etype`

**Comment by bthorben** [comment]
Looks like a good workaround!

**Comment by dkellner** [comment]
This should work by now in the current master branch.
